# _config.yml

# title: "Jekyll Actions Guide"
# description: "Setting up the Initial"

# url: "https://CMCD1996.github.io"
# baseurl: "/jekyll-actions-quickstart"

# github_username: CMCD1996

# markdown: kramdown
# theme: minima
# plugins:
#   - jekyll-timeago

title: Jacob Jones
email: jacob-jones-eb@gmail.com
github_username: jj-eb
instagram_username: _jacob.jones__
description:
linkedin_username: jacob-jones-974698166
collections:
  protected:

# Build settings
markdown: kramdown
mathjax: true
theme: minima
